### ISSUE TITLE
Missing return codes checks

### ISSUE THREAD

**Issue by leamas** [bengtmartensson/PythonLircClient#9]
Many (most?) commands does not check the command results => no usere feedback on errors. I have marked one with #FIXME, but it seems to be a general problem.

I also think that the difference between a completely between failed (syntax errors) and the ERROR return message. IIRC, there is not  enough information returned to be able  to cope with it.

One possibility is is to have send_command return the parser (with complete ststus available) instead of a single code.

**Comment by bengtmartensson** [comment]
> no usere feedback on errors.

Modern programming uses exceptions rather than return codes (see e.g. Martin, Clean code, page 104). And so does this program. So your statement is simply not true. That said, it is a bit disturbing that the api functions return a value that is ignored by the main function. Needs to be checked/fixed. Do you have any specific example?

**Comment by bengtmartensson** [comment]
Issue has been addressed -- but possibly differenty from the way you expected :-). Ok to close?
